### ISSUE TITLE
Search for action.yml files in the entire repository

### ISSUE THREAD

**Issue by rajbos** [devops-actions/load-available-actions#66]
Some repositories, like [codeql-action](https://github.com/github/codeql-action/) still use the old model of storing `action.yml` in 
several folders in the repo (this also prevents them from publishing the action to the marketplace btw). 

# codeql-action
The repo codeql-action has multiple action files store inside of it:

* [Init](https://github.com/github/codeql-action/tree/main/init)
* [Analyze](https://github.com/github/codeql-action/tree/main/analyze)

You can also see that from their usage inside of workflow files:
``` yaml
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

   - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
```

- [ ] Search for the yaml files in the entire repositories and add them as separate entries to the output
